import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PageWrapper from "@/components/PageWrapper";
import { ThemeProvider } from '@/app/context/ThemeContext';

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const geistNoticia = localFont({
	src: "./fonts/NoticiaText-Regular.woff",
	variable: "--font-noticia-text",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} ${geistNoticia.variable} antialiased overscroll-none bg-slate-50 fixed h-[100dvh] w-screen`}>
				<ThemeProvider>
					<PageWrapper>	
						{children}
					</PageWrapper>
				</ThemeProvider>
			</body>
		</html>
	);
}
